name: CI Pipeline

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  env-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn install -DskipTests

  build:
    runs-on: ubuntu-latest
    needs: env-setup
    steps:
      - name: Build project
        run: mvn package

  test:
    runs-on: ubuntu-latest
    needs: env-setup
    steps:
      - name: Run tests
        run: mvn test

#  checkstyle:
#    runs-on: ubuntu-latest
#    needs: env-setup
#    steps:
#      - name: Run Checkstyle
#        run: mvn checkstyle:check

  runSpotBugs:
    runs-on: ubuntu-latest
    needs: env-setup
    steps:
      - name: Run Spot Bugs
        run: mvn spotbugs:check

  runPMD:
    runs-on: ubuntu-latest
    needs: env-setup
    steps:
      - name: Run PMD
        run: mvn pmd:check

#  uploadArtifact:
#    runs-on: ubuntu-latest
#    needs: env-setup
#    uses: actions/upload-artifact@v3
#    with:
#      name: build-artifact
#      path: target/*.jar


