name: CI Pipeline

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  build-test-checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Build project
        run: mvn package

      - name: Run tests
        run: mvn test

#      - name: Run Checkstyle
#        run: mvn checkstyle:check

      - name: Run Spot Bugs
        run: mvn spotbugs:check

      - name: Run PMD
        run: mvn pmd:check

#  upload-artifact:
#    runs-on: ubuntu-latest
#    needs: build-test-checkstyle
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'adopt'
#
#      - name: Download .m2 directory
#        uses: actions/download-artifact@v3
#        with:
#          name: maven-cache
#          path: ~/.m2
#
#      - name: Upload artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: build-artifact
#          path: target/*.jar
